### ISSUE TITLE
to_renpy.py line 170 is attribute 'none'

### ISSUE THREAD

**Issue by noor-fernandez** [pass-by-reference/doc-to-renpy#1]
When I tried to convert my docx file it threw a python trace back with the error in the title. Could you fix this bug please?

**Comment by pass-by-reference** [comment]
Hi do you have the docx file and maybe the trace error handy so I can replicate the issue?

**Comment by noor-fernandez** [comment]
I do. Here is the document. Give me just a few minutes and I'll get the
trace error.

**Comment by noor-fernandez** [comment]
Holy cow it worked! I was gonna send you the trace but never mind it worked!
The only problem is it put the double quotes in front of the character definitions. But it didn't throw an error!

**Comment by pass-by-reference** [comment]
Hey I am glad it worked! I am still a little concerned of why it threw an error the first time but then it didn't. I don't see the document, but love to dig in some more.

**Comment by pass-by-reference** [comment]
Okay I am suspecting the issue is if document has no characters in the first line of the docx, it will throw an error.

I ran into this issue before and I thought I fixed it but it seems like I forgot to push it.

**Comment by noor-fernandez** [comment]
Did you find the document? Because I think you're right the new document I
has was truncated from the old version.

**Comment by pass-by-reference** [comment]
I wasn't able to find the document, but pushed some changes that should prevent that error from popping up again. 

If you are interested here is the PR: https://github.com/pass-by-reference/doc-to-renpy/pull/2/files

**Comment by noor-fernandez** [comment]
Thanks for looking into this. I really appreciate your tool and dedication.
